### ISSUE TITLE
Issue in the translation

### ISSUE THREAD

**Issue by davidegiacomelli** [MicrosoftDocs/sql-docs.it-it#8]
If you look at this section in documention

https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/relational-databases/spatial/spatial-data-types-overview.md#confronto-tra-linestring-e-circularstring

you can read that document talks about triangle but figure shows circles and linestring, 
So the example is not so clear.

**Comment by CeciAc** [comment]
Assigned to @carolinacmoravia since this looks like a source Issue but cannot move it myself to the en-us repository @ishasahni1

**Comment by ishasahni1** [comment]
@davidegiacomelli Thank you so much for your valuable feedback. The below feedback was shared with the content team and they have made the fixes as per the suggested feedback. The updated topic will be pushed out for localization next week and will be localized in a week time.
@CeciAc FYI.
