### ISSUE TITLE
il link per scaricare SSMS è rotto

### ISSUE THREAD

**Issue by Tharnadar** [MicrosoftDocs/sql-docs.it-it#92]
manco Emilio Fede...

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Scaricare SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @Tharnadar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Ciao, @Tharnadar 

Il collegamento verrà aggiornato automaticamente nel prossimo round di localizzazione.

Grazie per il tuo contributo.

**Comment by vtontodonato-c** [comment]
E cioè quando?? Sono 4 giorni ormai e non è ancora disponibile ?!

**Comment by landlogicit** [comment]
link corretto: https://go.microsoft.com/fwlink/?linkid=2105412
