### ISSUE TITLE
Download non funzionante

### ISSUE THREAD

**Issue by giapelle** [MicrosoftDocs/sql-docs.it-it#96]
Il link per scaricare il file https://go.microsoft.com/fwlink/?linkid=2104251 non funziona, rimanda alla home page di Microsoft.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Scaricare SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @giapelle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Ciao @giapelle

Il file è attualmente in fase di localizzazione. Sarà aggiornato presto.

Grazie
