### ISSUE TITLE
La pagina di azure data studio non è allineata all'inglese

### ISSUE THREAD

**Issue by matteosaporiti** [MicrosoftDocs/sql-docs.it-it#97]
La pagina in italiano contiene ancora, tra i motivi per usare Azure Data Studio, "se lo vi vuole", punto rimosso dalla pagina inglese in seguito alla seguente issue:
https://github.com/MicrosoftDocs/sql-docs/issues/3778

Dato che il punto sembra un po' una presa in giro credo valga la pena di rimuoverlo.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: bbe4ef3a-6282-5c51-5810-c6d63f3a0e1b
* Version Independent ID: 6d655e24-fc84-aad0-2422-2451cfb1ad34
* Content: [Informazioni su Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/it-it/sql/azure-data-studio/what-is?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/what-is.md](https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/azure-data-studio/what-is.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @matteosaporiti
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Ciao, @matteosaporiti 
Apprezziamo sinceramente il tuo commento e ci impegniamo per migliorare la tua esperienza su docs.microsoft.com. Ci servono tuttavia altre informazioni per poter gestire i tuoi commenti e suggerimenti. Potresti fornire informazioni più dettagliate e chiarire il tuo commento?

Cordiali saluti,
Microsoft DOCS International Team

**Comment by matteosaporiti** [comment]
Ciao @CeciAc 
Questo è quanto si vede attualmente nella pagina italiana
![image](https://user-images.githubusercontent.com/3509455/72417827-f806ff00-3779-11ea-9a10-3a61ac3edb55.png)
Il punto selezionato è stato rimosso dalla documentazione inglese circa un mese fa, in questo commit
https://github.com/MicrosoftDocs/sql-docs/commit/8a4580a623157d0b28da94a70d87a45eb0b547a9#diff-ef3bd1e3e9510475a44e220b50a9ea21

Saluti,

Matteo

**Comment by ticianaciminari** [comment]
@matteosaporiti 

Grazie per i commenti e i suggerimenti inviati.  

 Il team tecnico ha esaminato e accettato i tuoi suggerimenti. I suggerimenti sono stati implementati e pubblicati negli articoli aggiornati sul sito Docs nelle pagine seguenti https://docs.microsoft.com/it-it/sql/azure-data-studio/what-is?view=sql-server-ver15
![image](https://user-images.githubusercontent.com/43826292/72830369-5727b080-3c5f-11ea-88e6-7ef422c75b70.png)

Il tuo contributo ai nostri articoli è molto apprezzato e ci auguriamo che vorrai continuare a inviarci i tuoi utili suggerimenti.  

Cordiali saluti,  

Il team internazionale Microsoft Docs
