### ISSUE TITLE
keywords translated in Italian

### ISSUE THREAD

**Issue by conky77** [MicrosoftDocs/sql-docs.it-it#98]
Some keywords are translated into  Italian, and it is challenging to guess them.

### Main section
- A -->TO
- ATTIVA-->active
- Elimina-->delete
- USA-->use
- o-->or
- Torna all'inizio-->TOP

### Section: Parole chiave riservate di ODBC
- ora -->time

### Section: Parole chiave di versioni future
- nessuno -->none
- parametro-->parameter
- valore-->value

### Other keywords translated
On the left tree index, some functions/keywords are translated into Italian

- USA-->USE
- CONCATENA-->CONCAT

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Parole chiave riservate (Transact-SQL) - SQL Server](https://docs.microsoft.com/it-it/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @conky77
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @conky77,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
